/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.grupo11.gui;

//import org.grupo11.bomberman.Juego;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import org.grupo11.bomberman.LoggedUser;
import org.grupo11.bomberman.Map;


/**
 *
 * @author Jose Morente
 */
public class GameView extends javax.swing.JFrame {
    /**
     * PROPIEDADES JUEGO 
     */
    
    
    /**
     * Creates new form Bomberman
     */
    public GameView() {
        //userText.setText(LoggedUser.Nsesion);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedorJuego = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        userText = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1240, 740));
        setResizable(false);
        setSize(new java.awt.Dimension(1240, 740));
        getContentPane().setLayout(null);

        javax.swing.GroupLayout contenedorJuegoLayout = new javax.swing.GroupLayout(contenedorJuego);
        contenedorJuego.setLayout(contenedorJuegoLayout);
        contenedorJuegoLayout.setHorizontalGroup(
            contenedorJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );
        contenedorJuegoLayout.setVerticalGroup(
            contenedorJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );

        getContentPane().add(contenedorJuego);
        contenedorJuego.setBounds(0, 0, 710, 710);

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("jLabel5");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(880, 610, 80, 30);

        userText.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        userText.setForeground(new java.awt.Color(255, 255, 255));
        userText.setText("jLabel4");
        getContentPane().add(userText);
        userText.setBounds(880, 530, 80, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("jLabel4");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(880, 570, 80, 30);

        jButton1.setText("jButton1");
        getContentPane().add(jButton1);
        jButton1.setBounds(850, 580, 79, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/grupo11/recursos/Juego.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1280, 720);

        jMenuBar1.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N

        jMenu1.setText("Juego");
        jMenu1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jMenuItem1.setText("Nuevo Juego");
        jMenuItem1.setToolTipText("");
        jMenu1.add(jMenuItem1);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jMenuItem4.setText("Cargar Archivo");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");
        jMenu2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N

        jMenuItem2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jMenuItem2.setText("Documentación");
        jMenu2.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jMenuItem3.setText("Acerca De");
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        String auxiliar = "";
        String text = "";
        String rute = "";
        
        JFileChooser JfC = new JFileChooser();
        JfC.setAcceptAllFileFilterUsed(false);
        //JfC.setFileFilter(new FileNameExtensionFilter("Archivos con extension *." + Filtro_Archivo, Filtro_Archivo));
        JfC.setCurrentDirectory(new File("Desktop"));
        JfC.showOpenDialog(null);
        File Archivo = JfC.getSelectedFile();
        if (Archivo != null) {
                rute = "" + Archivo;
                FileReader FR;
            try {
                FR = new FileReader(Archivo);
                
                
                try (BufferedReader Buffer = new BufferedReader(FR)) {
                    while ((auxiliar = Buffer.readLine()) != null) {
                        text += auxiliar + "\n";
                    }
//                    System.out.println(texto);
                }catch (IOException e) {
                    System.out.println("ERROR");
                }
                
            LoggedUser.MUNDO = text;
                
            Map mapa=new Map();
            mapa.CrearMapa(); 
            
            } catch (FileNotFoundException ex) {
                Logger.getLogger(GameView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameView().setVisible(true);
            }
        });
        
        
    }
    
    /*
	|--------------------------------------------------------------------------
	| Game Related
	|--------------------------------------------------------------------------
	 */
  /*  public void newGame() {
        _game.getBoard().newJuego();
    }

    public void changeLevel(int i) {
            _game.getBoard().changeLevel(i);
    }

    public void pauseGame() {
            _game.getBoard().gamePause();
    }

    public void resumeGame() {
            _game.getBoard().gameResume();
    }

    public boolean isRunning() {
            return _game.isRunning();
    }
*/
    //MOSTRAR TIEMPO
    public void setTime(int time) {
        this.jLabel3.setText(String.valueOf(time));
    }

    //MOSTRAR VIDAS
    public void setLives(int lives) {
        this.userText.setText(String.valueOf(lives));
    }

    //MOSTRAR PUNTOS
    public void setPoints(int points) {
        this.userText.setText(String.valueOf(points));
    }

    /*public boolean validCode(String str) {
            return _game.getBoard().getLevel().validCode(str) != -1;
    }

    public void changeLevelByCode(String str) {
            _game.getBoard().changeLevelByCode(str);
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenedorJuego;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JLabel userText;
    // End of variables declaration//GEN-END:variables
}
