/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.grupo11.gui;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import org.grupo11.bomberman.LoggedUser;
import org.grupo11.bomberman.ThreadGame;

/**
 *
 * @author Juan José Ramos
 */
public class Game extends javax.swing.JFrame {

    /**
     * Creates new form Game
     */
    public Game() {
        initComponents();
        LoggedUser.tgame.life = 3;
        LoggedUser.tgame = new ThreadGame(jTable1,life,time);

        KeyListener kl = new KeyListener() {
            @Override
            public void keyTyped(KeyEvent ke) {
            }

            @Override
            public void keyPressed(KeyEvent ke) {
                System.out.print("entro");
            }

            @Override
            public void keyReleased(KeyEvent ke) {
            if (ke.getKeyCode() == KeyEvent.VK_LEFT) {
                //IZQUIEDA
                    ThreadGame.movement = 1;
                    System.out.println("IZQUIEDA");
                }
            if (ke.getKeyCode() == KeyEvent.VK_RIGHT) {
                //DERCHA
                    ThreadGame.movement = 2;
                    System.out.println("DERCHA");
                }
            if (ke.getKeyCode() == KeyEvent.VK_UP) {
                //ARRIBA
                    ThreadGame.movement = 3;
                    System.out.println("ARRIBA");
                }
            if (ke.getKeyCode() == KeyEvent.VK_DOWN) {
                //ABAJO
                    ThreadGame.movement = 4;
                    System.out.println("ABAJO");
                }
            if (ke.getKeyCode() == KeyEvent.VK_P) {
                //ABAJO
                    ThreadGame.movement = 5;
                    System.out.println("PAUSA");
                }
            if (ke.getKeyCode() == KeyEvent.VK_A) {
                //BOMBA (A)
                    ThreadGame.movement = 6;
                    System.out.println("BOMBA");
                }
            
            }
            
        };
        this.addKeyListener(kl);
        
        //Mostrar();
        LoggedUser.tgame.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        life = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1240, 740));
        getContentPane().setLayout(null);

        jTable1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable1.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setFocusable(false);
        jTable1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable1.setMaximumSize(new java.awt.Dimension(0, 0));
        jTable1.setMinimumSize(new java.awt.Dimension(0, 0));
        jTable1.setRowHeight(50);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 720, 720);

        life.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        life.setForeground(new java.awt.Color(255, 255, 255));
        life.setText("--");
        getContentPane().add(life);
        life.setBounds(1010, 550, 50, 30);

        time.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        time.setForeground(new java.awt.Color(255, 255, 255));
        time.setText("--");
        getContentPane().add(time);
        time.setBounds(1010, 590, 50, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Life:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(940, 550, 40, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Time:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(940, 590, 60, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/grupo11/recursos/Juego.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel life;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
}
