/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;

/**
 *
 * @author Jose Morente
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    private final pPort port;
    public static String [][] Pausa =
    {
        {"X","X","X","X","X","X","X","X","X","X","X","X"},
        {"X"," "," "," "," "," "," "," "," "," "," ","X"},
        {"X"," "," "," "," "," "," "," "," "," "," ","X"},
        {"X"," "," "," "," "," "," "," "," "," "," ","X"},
        {"X"," "," "," "," "," "," "," "," "," "," ","X"},
        {"X"," "," "," "," "," "," "," "," "," "," ","X"},
        {"X"," "," "," "," "," "," "," "," "," "," ","X"},
        {"X"," "," "," "," "," "," "," "," "," "," ","X"},
        {"X"," "," "," "," "," "," "," "," "," "," ","X"},
        {"X"," "," "," "," "," "," "," "," "," "," ","X"},
        {"X"," "," "," "," "," "," "," "," "," "," ","X"},
        {"X","X","X","X","X","X","X","X","X","X","X","X"}
    };
    private Timer timer = new Timer();
    private TimerTask timerTask;
    
    
    public Login() {
        setFocusable(true);
        requestFocus();
        initComponents();
        port = new pPort();
        port.setAllDataBits((short) 0); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        loginButton1 = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 740));
        setSize(new java.awt.Dimension(1280, 740));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 100)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Inicio de Sesión");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 50, 880, 210);

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Usuario");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 320, 150, 40);

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("¿No tienes una cuenta?");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(250, 570, 257, 40);

        user.setFont(new java.awt.Font("Segoe UI Light", 0, 22)); // NOI18N
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        getContentPane().add(user);
        user.setBounds(70, 370, 250, 40);

        jButton1.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jButton1.setText("Registrarme");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(250, 610, 250, 40);

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cotraseña");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 410, 170, 40);

        loginButton1.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        loginButton1.setText("Iniciar Sesión");
        loginButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(loginButton1);
        loginButton1.setBounds(70, 520, 250, 40);
        getContentPane().add(password);
        password.setBounds(70, 460, 250, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/grupo11/recursos/Wallpaper.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 1280, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Register rg = new Register();
        rg.setVisible(true);
        this.setVisible(false);
        //Bomberman bomberman = new Bomberman();
        //bomberman.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    public void reloj(int puerto, int bit, int tiempo) {
        timerTask = new TimerTask()
        {
            public void run() 
            {
                // Aquí el código que queremos ejecutar.
                port.setPin((short) puerto, (short) bit); 
            }
        };
        // Dentro de 0 milisegundos avísame cada 1 milisegundos
        timer.scheduleAtFixedRate(timerTask, 1000, tiempo);
    }

    private void loginButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButton1ActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < 11; i++) {
            for (int j = 0; j < 12; j++) {
                port.setPin((short) 2, (short) 0);
                port.setPin((short) 3, (short) 1);
                for (int k = 0; k < 1001; k++) {
                    if(k==1000) {
                        port.setPin((short) 3, (short) 0);
                    }
                }
            }
        }
        
       
        String pass = (new String(password.getPassword()));
        if (user.getText().equals("ADMIN") && pass.toString().equals("ORGA_DIC_2019")) {
            LoggedUser.Nsesion = "ADMIN";
            JOptionPane.showMessageDialog(null, user.getText() + " " + pass);
            Administrador admin = new Administrador();
            admin.setVisible(true);
            JOptionPane.showMessageDialog(null, "Bienvenido administrador");
            this.setVisible(false);
            
        } else if(user.getText().equals("a") && pass.toString().equals("a")){
            LoggedUser.Nsesion = "a";
                        JOptionPane.showMessageDialog(null, "Bienvenido "+ this.user.getText());
                        Usuario gv = new Usuario();
                        gv.setVisible(true);
                        this.setVisible(false);
        }
        else if(user.getText().equals("") || pass.equals("") ) {
            JOptionPane.showMessageDialog(null, "No puede dejar campos en blanco");
            
        } else {
            boolean existente = false;
            for (User user : LoggedUser.solicitud) {
                if (user.getUsername().equals(this.user.getText()) && user.getPassword().equals(pass)) {
                    existente = true;
                    if (user.getAprovacion() == true) {
                        LoggedUser.Nsesion = user.getUsername();
                        JOptionPane.showMessageDialog(null, "Bienvenido "+ this.user.getText());
                        Usuario gv = new Usuario();
                        gv.setVisible(true);
                        this.setVisible(false);

                    } else {
                        JOptionPane.showMessageDialog(null, "Su cuenta no se ha aprovado todavía");
                    }
                }
            }
            if (existente == false) {
                JOptionPane.showMessageDialog(null, "Usuario no encontrado");
            }
        }
        
        
        
        
        
        /*for (int i = 0; i < 12; i++) {
            for (int j = 0; j < 12; j++) {
                port.setPin((short) 2, (short) 0);
                port.setPin((short) 3, (short) 1);
                for (int k = 0; k < 1001; k++) {
                            if(k==1000) {
                                port.setPin((short) 3, (short) 0);
                            }
                }
            }
        }
        /*for (int x = 0; x < 5000; x++) {
            for (int i = 0; i < 12; i++) {
            //System.out.println(i);
                for (int j = 0; j < 12; j++) {
                    if(Pausa[i][j].equals("X")) {
                        port.setPin((short) 2, (short) 1);
                        port.setPin((short) 3, (short) 1);
                        port.setPin((short) 3, (short) 0);
                    } else if(Pausa[i][j].equals(" ")) {
                        port.setPin((short) 2, (short) 0);
                        port.setPin((short) 3, (short) 1);
                        port.setPin((short) 3, (short) 0);
                    }
                }
            }
        }
        
        /*for (int x = 0; x < 5000; x++) {
            for (int i = 0; i < 12; i++) {
            //System.out.println(i);
            for (int j = 0; j < 12; j++) {
                if(Pausa[i][j].equals("X")) {
                    port.setPin((short) 2, (short) 1);
                    port.setPin((short) 3, (short) 1);
                    for (int k = 0; k < 2000; k++) {
                        System.err.println(k);
                        if(k==1999) {
                            port.setPin((short) 3, (short) 0);
                        }
                    }                            
                    
                    /*timerTask = new TimerTask()
                    {
                        public void run() 
                        {
                            // Aquí el código que queremos ejecutar.
                            //port.setPin((short) puerto, (short) bit);
                            port.setPin((short) 2, (short) 1); 
                            port.setPin((short) 3, (short) 1);
                            reloj(3, 0, 1000);
                        }
                    };*/
                    // Dentro de 0 milisegundos avísame cada 1 milisegundos
                   // timer.scheduleAtFixedRate(timerTask, 1000, 1000);
                /*} else if(Pausa[i][j].equals(" ")) {
                    port.setPin((short) 2, (short) 0);
                    port.setPin((short) 3, (short) 1);
                    for (int k = 0; k < 2000; k++) {
                        System.err.println(k);
                        if(k==1999) {
                            port.setPin((short) 3, (short) 0);
                        }
                    }  
                    /*timerTask = new TimerTask()
                    {
                        public void run() 
                        {
                            // Aquí el código que queremos ejecutar.
                            //port.setPin((short) puerto, (short) bit);
                            port.setPin((short) 2, (short) 0); 
                            port.setPin((short) 3, (short) 1);
                            reloj(3, 0, 1000);
                        }
                    };
                    // Dentro de 0 milisegundos avísame cada 1 milisegundos
                    timer.scheduleAtFixedRate(timerTask, 1000, 1000);*/
        /*        }
            }
        }
        }*/
        
    }//GEN-LAST:event_loginButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Metal look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Metal (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                System.out.println(info.getName());
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //Campo c = new Campo();

                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton loginButton1;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
